/* this file is generated by com.deploy.Deploy */
import React from 'react';
class ToghVersion extends React.Component {
  render() {
    return ("janv. 15, 2023 12:58")
  }}export default ToghVersion;