name: 1-worker-build-publish-image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    name: 1-worker-publish-build - ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # to publish to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest