# build environment
FROM node:12.4.0-alpine as build
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./


RUN npm install --silent
# RUN npm install react-scripts@3.0.1 -g 
# RUN npm install --save-dev react-dev-utils
# RUN npm install fs-extra

COPY . ./
RUN npm install --production
RUN npm run build

# production environment
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

# RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]